// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/forestvpn/go-api-client-v1/models"
)

// GetPremiumReader is a Reader for the GetPremium structure.
type GetPremiumReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPremiumReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPremiumOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetPremiumDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetPremiumOK creates a GetPremiumOK with default headers values
func NewGetPremiumOK() *GetPremiumOK {
	return &GetPremiumOK{}
}

/* GetPremiumOK describes a response with status code 200, with default header values.

OK
*/
type GetPremiumOK struct {
	Payload *models.Subscription
}

func (o *GetPremiumOK) Error() string {
	return fmt.Sprintf("[GET /user/premium/][%d] getPremiumOK  %+v", 200, o.Payload)
}
func (o *GetPremiumOK) GetPayload() *models.Subscription {
	return o.Payload
}

func (o *GetPremiumOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Subscription)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPremiumDefault creates a GetPremiumDefault with default headers values
func NewGetPremiumDefault(code int) *GetPremiumDefault {
	return &GetPremiumDefault{
		_statusCode: code,
	}
}

/* GetPremiumDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type GetPremiumDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get premium default response
func (o *GetPremiumDefault) Code() int {
	return o._statusCode
}

func (o *GetPremiumDefault) Error() string {
	return fmt.Sprintf("[GET /user/premium/][%d] GetPremium default  %+v", o._statusCode, o.Payload)
}
func (o *GetPremiumDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPremiumDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
