// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPremiumParams creates a new GetPremiumParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPremiumParams() *GetPremiumParams {
	return &GetPremiumParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPremiumParamsWithTimeout creates a new GetPremiumParams object
// with the ability to set a timeout on a request.
func NewGetPremiumParamsWithTimeout(timeout time.Duration) *GetPremiumParams {
	return &GetPremiumParams{
		timeout: timeout,
	}
}

// NewGetPremiumParamsWithContext creates a new GetPremiumParams object
// with the ability to set a context for a request.
func NewGetPremiumParamsWithContext(ctx context.Context) *GetPremiumParams {
	return &GetPremiumParams{
		Context: ctx,
	}
}

// NewGetPremiumParamsWithHTTPClient creates a new GetPremiumParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPremiumParamsWithHTTPClient(client *http.Client) *GetPremiumParams {
	return &GetPremiumParams{
		HTTPClient: client,
	}
}

/* GetPremiumParams contains all the parameters to send to the API endpoint
   for the get premium operation.

   Typically these are written to a http.Request.
*/
type GetPremiumParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get premium params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPremiumParams) WithDefaults() *GetPremiumParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get premium params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPremiumParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get premium params
func (o *GetPremiumParams) WithTimeout(timeout time.Duration) *GetPremiumParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get premium params
func (o *GetPremiumParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get premium params
func (o *GetPremiumParams) WithContext(ctx context.Context) *GetPremiumParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get premium params
func (o *GetPremiumParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get premium params
func (o *GetPremiumParams) WithHTTPClient(client *http.Client) *GetPremiumParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get premium params
func (o *GetPremiumParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPremiumParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
