// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/forestvpn/go-api-client-v1/models"
)

// CreateProfileReader is a Reader for the CreateProfile structure.
type CreateProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateProfileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateProfileOK creates a CreateProfileOK with default headers values
func NewCreateProfileOK() *CreateProfileOK {
	return &CreateProfileOK{}
}

/* CreateProfileOK describes a response with status code 200, with default header values.

OK
*/
type CreateProfileOK struct {
	Payload *models.WireGuardProfile
}

func (o *CreateProfileOK) Error() string {
	return fmt.Sprintf("[POST /wg/profiles/][%d] createProfileOK  %+v", 200, o.Payload)
}
func (o *CreateProfileOK) GetPayload() *models.WireGuardProfile {
	return o.Payload
}

func (o *CreateProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WireGuardProfile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateProfileDefault creates a CreateProfileDefault with default headers values
func NewCreateProfileDefault(code int) *CreateProfileDefault {
	return &CreateProfileDefault{
		_statusCode: code,
	}
}

/* CreateProfileDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type CreateProfileDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create profile default response
func (o *CreateProfileDefault) Code() int {
	return o._statusCode
}

func (o *CreateProfileDefault) Error() string {
	return fmt.Sprintf("[POST /wg/profiles/][%d] CreateProfile default  %+v", o._statusCode, o.Payload)
}
func (o *CreateProfileDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateProfileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
