// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProfilesParams creates a new GetProfilesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProfilesParams() *GetProfilesParams {
	return &GetProfilesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProfilesParamsWithTimeout creates a new GetProfilesParams object
// with the ability to set a timeout on a request.
func NewGetProfilesParamsWithTimeout(timeout time.Duration) *GetProfilesParams {
	return &GetProfilesParams{
		timeout: timeout,
	}
}

// NewGetProfilesParamsWithContext creates a new GetProfilesParams object
// with the ability to set a context for a request.
func NewGetProfilesParamsWithContext(ctx context.Context) *GetProfilesParams {
	return &GetProfilesParams{
		Context: ctx,
	}
}

// NewGetProfilesParamsWithHTTPClient creates a new GetProfilesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProfilesParamsWithHTTPClient(client *http.Client) *GetProfilesParams {
	return &GetProfilesParams{
		HTTPClient: client,
	}
}

/* GetProfilesParams contains all the parameters to send to the API endpoint
   for the get profiles operation.

   Typically these are written to a http.Request.
*/
type GetProfilesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get profiles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProfilesParams) WithDefaults() *GetProfilesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get profiles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProfilesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get profiles params
func (o *GetProfilesParams) WithTimeout(timeout time.Duration) *GetProfilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get profiles params
func (o *GetProfilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get profiles params
func (o *GetProfilesParams) WithContext(ctx context.Context) *GetProfilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get profiles params
func (o *GetProfilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get profiles params
func (o *GetProfilesParams) WithHTTPClient(client *http.Client) *GetProfilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get profiles params
func (o *GetProfilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetProfilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
