// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/forestvpn/go-api-client-v1/models"
)

// GetProfileReader is a Reader for the GetProfile structure.
type GetProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetProfileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetProfileOK creates a GetProfileOK with default headers values
func NewGetProfileOK() *GetProfileOK {
	return &GetProfileOK{}
}

/* GetProfileOK describes a response with status code 200, with default header values.

OK
*/
type GetProfileOK struct {
	Payload *models.WireGuardProfile
}

func (o *GetProfileOK) Error() string {
	return fmt.Sprintf("[GET /wg/profiles/{profileId}/][%d] getProfileOK  %+v", 200, o.Payload)
}
func (o *GetProfileOK) GetPayload() *models.WireGuardProfile {
	return o.Payload
}

func (o *GetProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WireGuardProfile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProfileDefault creates a GetProfileDefault with default headers values
func NewGetProfileDefault(code int) *GetProfileDefault {
	return &GetProfileDefault{
		_statusCode: code,
	}
}

/* GetProfileDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type GetProfileDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get profile default response
func (o *GetProfileDefault) Code() int {
	return o._statusCode
}

func (o *GetProfileDefault) Error() string {
	return fmt.Sprintf("[GET /wg/profiles/{profileId}/][%d] GetProfile default  %+v", o._statusCode, o.Payload)
}
func (o *GetProfileDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetProfileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
