// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/forestvpn/go-api-client-v1/models"
)

// UpdateProfileReader is a Reader for the UpdateProfile structure.
type UpdateProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUpdateProfileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateProfileOK creates a UpdateProfileOK with default headers values
func NewUpdateProfileOK() *UpdateProfileOK {
	return &UpdateProfileOK{}
}

/* UpdateProfileOK describes a response with status code 200, with default header values.

OK
*/
type UpdateProfileOK struct {
	Payload *models.WireGuardProfile
}

func (o *UpdateProfileOK) Error() string {
	return fmt.Sprintf("[PATCH /wg/profiles/{profileId}/][%d] updateProfileOK  %+v", 200, o.Payload)
}
func (o *UpdateProfileOK) GetPayload() *models.WireGuardProfile {
	return o.Payload
}

func (o *UpdateProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WireGuardProfile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateProfileDefault creates a UpdateProfileDefault with default headers values
func NewUpdateProfileDefault(code int) *UpdateProfileDefault {
	return &UpdateProfileDefault{
		_statusCode: code,
	}
}

/* UpdateProfileDefault describes a response with status code -1, with default header values.

error
*/
type UpdateProfileDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the update profile default response
func (o *UpdateProfileDefault) Code() int {
	return o._statusCode
}

func (o *UpdateProfileDefault) Error() string {
	return fmt.Sprintf("[PATCH /wg/profiles/{profileId}/][%d] UpdateProfile default  %+v", o._statusCode, o.Payload)
}
func (o *UpdateProfileDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateProfileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
