// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/forestvpn/go-api-client-v1/models"
)

// NewUpdateProfileParams creates a new UpdateProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateProfileParams() *UpdateProfileParams {
	return &UpdateProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateProfileParamsWithTimeout creates a new UpdateProfileParams object
// with the ability to set a timeout on a request.
func NewUpdateProfileParamsWithTimeout(timeout time.Duration) *UpdateProfileParams {
	return &UpdateProfileParams{
		timeout: timeout,
	}
}

// NewUpdateProfileParamsWithContext creates a new UpdateProfileParams object
// with the ability to set a context for a request.
func NewUpdateProfileParamsWithContext(ctx context.Context) *UpdateProfileParams {
	return &UpdateProfileParams{
		Context: ctx,
	}
}

// NewUpdateProfileParamsWithHTTPClient creates a new UpdateProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateProfileParamsWithHTTPClient(client *http.Client) *UpdateProfileParams {
	return &UpdateProfileParams{
		HTTPClient: client,
	}
}

/* UpdateProfileParams contains all the parameters to send to the API endpoint
   for the update profile operation.

   Typically these are written to a http.Request.
*/
type UpdateProfileParams struct {

	// ProfileID.
	//
	// Format: uuid
	ProfileID strfmt.UUID

	// Request.
	Request *models.WireGuardProfileUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateProfileParams) WithDefaults() *UpdateProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update profile params
func (o *UpdateProfileParams) WithTimeout(timeout time.Duration) *UpdateProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update profile params
func (o *UpdateProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update profile params
func (o *UpdateProfileParams) WithContext(ctx context.Context) *UpdateProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update profile params
func (o *UpdateProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update profile params
func (o *UpdateProfileParams) WithHTTPClient(client *http.Client) *UpdateProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update profile params
func (o *UpdateProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProfileID adds the profileID to the update profile params
func (o *UpdateProfileParams) WithProfileID(profileID strfmt.UUID) *UpdateProfileParams {
	o.SetProfileID(profileID)
	return o
}

// SetProfileID adds the profileId to the update profile params
func (o *UpdateProfileParams) SetProfileID(profileID strfmt.UUID) {
	o.ProfileID = profileID
}

// WithRequest adds the request to the update profile params
func (o *UpdateProfileParams) WithRequest(request *models.WireGuardProfileUpdateRequest) *UpdateProfileParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the update profile params
func (o *UpdateProfileParams) SetRequest(request *models.WireGuardProfileUpdateRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param profileId
	if err := r.SetPathParam("profileId", o.ProfileID.String()); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
