// Code generated by go-swagger; DO NOT EDIT.

package google

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/forestvpn/go-api-client-v1/models"
)

// VerifyGooglePlayPurchaseReader is a Reader for the VerifyGooglePlayPurchase structure.
type VerifyGooglePlayPurchaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VerifyGooglePlayPurchaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVerifyGooglePlayPurchaseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVerifyGooglePlayPurchaseDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVerifyGooglePlayPurchaseOK creates a VerifyGooglePlayPurchaseOK with default headers values
func NewVerifyGooglePlayPurchaseOK() *VerifyGooglePlayPurchaseOK {
	return &VerifyGooglePlayPurchaseOK{}
}

/* VerifyGooglePlayPurchaseOK describes a response with status code 200, with default header values.

OK
*/
type VerifyGooglePlayPurchaseOK struct {
}

func (o *VerifyGooglePlayPurchaseOK) Error() string {
	return fmt.Sprintf("[POST /google/verify-purchase/][%d] verifyGooglePlayPurchaseOK ", 200)
}

func (o *VerifyGooglePlayPurchaseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewVerifyGooglePlayPurchaseDefault creates a VerifyGooglePlayPurchaseDefault with default headers values
func NewVerifyGooglePlayPurchaseDefault(code int) *VerifyGooglePlayPurchaseDefault {
	return &VerifyGooglePlayPurchaseDefault{
		_statusCode: code,
	}
}

/* VerifyGooglePlayPurchaseDefault describes a response with status code -1, with default header values.

error
*/
type VerifyGooglePlayPurchaseDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the verify google play purchase default response
func (o *VerifyGooglePlayPurchaseDefault) Code() int {
	return o._statusCode
}

func (o *VerifyGooglePlayPurchaseDefault) Error() string {
	return fmt.Sprintf("[POST /google/verify-purchase/][%d] VerifyGooglePlayPurchase default  %+v", o._statusCode, o.Payload)
}
func (o *VerifyGooglePlayPurchaseDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *VerifyGooglePlayPurchaseDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
