// Code generated by go-swagger; DO NOT EDIT.

package google

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/forestvpn/go-api-client-v1/models"
)

// NewVerifyGooglePlayPurchaseParams creates a new VerifyGooglePlayPurchaseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVerifyGooglePlayPurchaseParams() *VerifyGooglePlayPurchaseParams {
	return &VerifyGooglePlayPurchaseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVerifyGooglePlayPurchaseParamsWithTimeout creates a new VerifyGooglePlayPurchaseParams object
// with the ability to set a timeout on a request.
func NewVerifyGooglePlayPurchaseParamsWithTimeout(timeout time.Duration) *VerifyGooglePlayPurchaseParams {
	return &VerifyGooglePlayPurchaseParams{
		timeout: timeout,
	}
}

// NewVerifyGooglePlayPurchaseParamsWithContext creates a new VerifyGooglePlayPurchaseParams object
// with the ability to set a context for a request.
func NewVerifyGooglePlayPurchaseParamsWithContext(ctx context.Context) *VerifyGooglePlayPurchaseParams {
	return &VerifyGooglePlayPurchaseParams{
		Context: ctx,
	}
}

// NewVerifyGooglePlayPurchaseParamsWithHTTPClient creates a new VerifyGooglePlayPurchaseParams object
// with the ability to set a custom HTTPClient for a request.
func NewVerifyGooglePlayPurchaseParamsWithHTTPClient(client *http.Client) *VerifyGooglePlayPurchaseParams {
	return &VerifyGooglePlayPurchaseParams{
		HTTPClient: client,
	}
}

/* VerifyGooglePlayPurchaseParams contains all the parameters to send to the API endpoint
   for the verify google play purchase operation.

   Typically these are written to a http.Request.
*/
type VerifyGooglePlayPurchaseParams struct {

	// Request.
	Request *models.GooglePlayPurchaseVerificationRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the verify google play purchase params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VerifyGooglePlayPurchaseParams) WithDefaults() *VerifyGooglePlayPurchaseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the verify google play purchase params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VerifyGooglePlayPurchaseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the verify google play purchase params
func (o *VerifyGooglePlayPurchaseParams) WithTimeout(timeout time.Duration) *VerifyGooglePlayPurchaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the verify google play purchase params
func (o *VerifyGooglePlayPurchaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the verify google play purchase params
func (o *VerifyGooglePlayPurchaseParams) WithContext(ctx context.Context) *VerifyGooglePlayPurchaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the verify google play purchase params
func (o *VerifyGooglePlayPurchaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the verify google play purchase params
func (o *VerifyGooglePlayPurchaseParams) WithHTTPClient(client *http.Client) *VerifyGooglePlayPurchaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the verify google play purchase params
func (o *VerifyGooglePlayPurchaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the verify google play purchase params
func (o *VerifyGooglePlayPurchaseParams) WithRequest(request *models.GooglePlayPurchaseVerificationRequest) *VerifyGooglePlayPurchaseParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the verify google play purchase params
func (o *VerifyGooglePlayPurchaseParams) SetRequest(request *models.GooglePlayPurchaseVerificationRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *VerifyGooglePlayPurchaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
