// Code generated by go-swagger; DO NOT EDIT.

package apple

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/forestvpn/go-api-client-v1/models"
)

// VerifyReceiptReader is a Reader for the VerifyReceipt structure.
type VerifyReceiptReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VerifyReceiptReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVerifyReceiptOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVerifyReceiptDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVerifyReceiptOK creates a VerifyReceiptOK with default headers values
func NewVerifyReceiptOK() *VerifyReceiptOK {
	return &VerifyReceiptOK{}
}

/* VerifyReceiptOK describes a response with status code 200, with default header values.

OK
*/
type VerifyReceiptOK struct {
}

func (o *VerifyReceiptOK) Error() string {
	return fmt.Sprintf("[POST /apple/verify-receipt/][%d] verifyReceiptOK ", 200)
}

func (o *VerifyReceiptOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewVerifyReceiptDefault creates a VerifyReceiptDefault with default headers values
func NewVerifyReceiptDefault(code int) *VerifyReceiptDefault {
	return &VerifyReceiptDefault{
		_statusCode: code,
	}
}

/* VerifyReceiptDefault describes a response with status code -1, with default header values.

error
*/
type VerifyReceiptDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the verify receipt default response
func (o *VerifyReceiptDefault) Code() int {
	return o._statusCode
}

func (o *VerifyReceiptDefault) Error() string {
	return fmt.Sprintf("[POST /apple/verify-receipt/][%d] VerifyReceipt default  %+v", o._statusCode, o.Payload)
}
func (o *VerifyReceiptDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *VerifyReceiptDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
