// Code generated by go-swagger; DO NOT EDIT.

package geo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/forestvpn/go-api-client-v1/models"
)

// GetCountriesReader is a Reader for the GetCountries structure.
type GetCountriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCountriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCountriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetCountriesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCountriesOK creates a GetCountriesOK with default headers values
func NewGetCountriesOK() *GetCountriesOK {
	return &GetCountriesOK{}
}

/* GetCountriesOK describes a response with status code 200, with default header values.

OK
*/
type GetCountriesOK struct {
	Payload []*models.Country
}

func (o *GetCountriesOK) Error() string {
	return fmt.Sprintf("[GET /countries/][%d] getCountriesOK  %+v", 200, o.Payload)
}
func (o *GetCountriesOK) GetPayload() []*models.Country {
	return o.Payload
}

func (o *GetCountriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCountriesDefault creates a GetCountriesDefault with default headers values
func NewGetCountriesDefault(code int) *GetCountriesDefault {
	return &GetCountriesDefault{
		_statusCode: code,
	}
}

/* GetCountriesDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type GetCountriesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get countries default response
func (o *GetCountriesDefault) Code() int {
	return o._statusCode
}

func (o *GetCountriesDefault) Error() string {
	return fmt.Sprintf("[GET /countries/][%d] GetCountries default  %+v", o._statusCode, o.Payload)
}
func (o *GetCountriesDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetCountriesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
