// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppleVerifyReceiptRequest apple verify receipt request
//
// swagger:model AppleVerifyReceiptRequest
type AppleVerifyReceiptRequest struct {

	// adv id
	AdvID string `json:"adv_id,omitempty"`

	// analytic ids
	AnalyticIds map[string]string `json:"analytic_ids,omitempty"`

	// currency
	Currency string `json:"currency,omitempty"`

	// price
	Price int64 `json:"price,omitempty"`

	// The latest Base64-encoded transaction receipt.
	// Format: byte
	Receipt strfmt.Base64 `json:"receipt,omitempty"`
}

// Validate validates this apple verify receipt request
func (m *AppleVerifyReceiptRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this apple verify receipt request based on context it is used
func (m *AppleVerifyReceiptRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppleVerifyReceiptRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppleVerifyReceiptRequest) UnmarshalBinary(b []byte) error {
	var res AppleVerifyReceiptRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
