// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GeoPoint geo point
//
// swagger:model GeoPoint
type GeoPoint struct {

	// latitude
	Latitude string `json:"latitude,omitempty"`

	// longitude
	Longitude string `json:"longitude,omitempty"`
}

// Validate validates this geo point
func (m *GeoPoint) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this geo point based on context it is used
func (m *GeoPoint) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GeoPoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GeoPoint) UnmarshalBinary(b []byte) error {
	var res GeoPoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
