// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GooglePlayPurchaseVerificationRequest google play purchase verification request
//
// swagger:model GooglePlayPurchaseVerificationRequest
type GooglePlayPurchaseVerificationRequest struct {

	// adv id
	AdvID string `json:"adv_id,omitempty"`

	// analytic ids
	AnalyticIds map[string]string `json:"analytic_ids,omitempty"`

	// The package name of the application that this notification relates to (for example, com.some.thing).
	PackageName string `json:"package_name,omitempty"`

	// The inapp product SKU (for example, 'com.some.thing.inapp1').
	ProductID string `json:"product_id,omitempty"`

	// The purchased subscription ID (for example, 'monthly001').
	SubscriptionID string `json:"subscription_id,omitempty"`

	// The token provided to the user's device when the inapp product was purchased.
	Token string `json:"token,omitempty"`
}

// Validate validates this google play purchase verification request
func (m *GooglePlayPurchaseVerificationRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this google play purchase verification request based on context it is used
func (m *GooglePlayPurchaseVerificationRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GooglePlayPurchaseVerificationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GooglePlayPurchaseVerificationRequest) UnmarshalBinary(b []byte) error {
	var res GooglePlayPurchaseVerificationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
