// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LookupRequest lookup request
//
// swagger:model LookupRequest
type LookupRequest struct {

	// name
	Name string `json:"name,omitempty"`

	// type
	// Enum: [any a]
	Type *string `json:"type,omitempty"`
}

// Validate validates this lookup request
func (m *LookupRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var lookupRequestTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["any","a"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		lookupRequestTypeTypePropEnum = append(lookupRequestTypeTypePropEnum, v)
	}
}

const (

	// LookupRequestTypeAny captures enum value "any"
	LookupRequestTypeAny string = "any"

	// LookupRequestTypeA captures enum value "a"
	LookupRequestTypeA string = "a"
)

// prop value enum
func (m *LookupRequest) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, lookupRequestTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *LookupRequest) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this lookup request based on context it is used
func (m *LookupRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LookupRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LookupRequest) UnmarshalBinary(b []byte) error {
	var res LookupRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
