// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProfilePreference profile preference
//
// swagger:model ProfilePreference
type ProfilePreference struct {

	// inbound location
	InboundLocation *Location `json:"inbound_location,omitempty"`

	// outbound location
	OutboundLocation *Location `json:"outbound_location,omitempty"`
}

// Validate validates this profile preference
func (m *ProfilePreference) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInboundLocation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOutboundLocation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProfilePreference) validateInboundLocation(formats strfmt.Registry) error {
	if swag.IsZero(m.InboundLocation) { // not required
		return nil
	}

	if m.InboundLocation != nil {
		if err := m.InboundLocation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("inbound_location")
			}
			return err
		}
	}

	return nil
}

func (m *ProfilePreference) validateOutboundLocation(formats strfmt.Registry) error {
	if swag.IsZero(m.OutboundLocation) { // not required
		return nil
	}

	if m.OutboundLocation != nil {
		if err := m.OutboundLocation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("outbound_location")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this profile preference based on the context it is used
func (m *ProfilePreference) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateInboundLocation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOutboundLocation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProfilePreference) contextValidateInboundLocation(ctx context.Context, formats strfmt.Registry) error {

	if m.InboundLocation != nil {
		if err := m.InboundLocation.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("inbound_location")
			}
			return err
		}
	}

	return nil
}

func (m *ProfilePreference) contextValidateOutboundLocation(ctx context.Context, formats strfmt.Registry) error {

	if m.OutboundLocation != nil {
		if err := m.OutboundLocation.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("outbound_location")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProfilePreference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProfilePreference) UnmarshalBinary(b []byte) error {
	var res ProfilePreference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
