// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WireGuardProfileUpdateRequest wire guard profile update request
//
// swagger:model WireGuardProfileUpdateRequest
type WireGuardProfileUpdateRequest struct {

	// inbound location id
	InboundLocationID string `json:"inbound_location_id,omitempty"`

	// outbound location id
	OutboundLocationID string `json:"outbound_location_id,omitempty"`
}

// Validate validates this wire guard profile update request
func (m *WireGuardProfileUpdateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this wire guard profile update request based on context it is used
func (m *WireGuardProfileUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WireGuardProfileUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WireGuardProfileUpdateRequest) UnmarshalBinary(b []byte) error {
	var res WireGuardProfileUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
