// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WireGuardInterface wire guard interface
//
// swagger:model WireGuardInterface
type WireGuardInterface struct {

	// address
	// Required: true
	Address []string `json:"address"`

	// dns
	DNS []string `json:"dns,omitempty"`

	// fw mark
	FwMark *string `json:"fw_mark,omitempty"`

	// listen port
	ListenPort *string `json:"listen_port,omitempty"`

	// private key
	// Required: true
	PrivateKey *string `json:"private_key"`

	// public key
	PublicKey string `json:"public_key,omitempty"`
}

// Validate validates this wire guard interface
func (m *WireGuardInterface) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrivateKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WireGuardInterface) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("address", "body", m.Address); err != nil {
		return err
	}

	return nil
}

func (m *WireGuardInterface) validatePrivateKey(formats strfmt.Registry) error {

	if err := validate.Required("private_key", "body", m.PrivateKey); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this wire guard interface based on context it is used
func (m *WireGuardInterface) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WireGuardInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WireGuardInterface) UnmarshalBinary(b []byte) error {
	var res WireGuardInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
